name: ci
on:
  push:
    # [push, pull_request]
    # update README badge only if the README file changes
    # or if the package.json file changes, or this file changes
    branches:
      - master
    paths:
      - src
      - package.json
      - .github/workflows/ci.yml
  pull_request:
    # [push, pull_request]
    # update README badge only if the README file changes
    # or if the package.json file changes, or this file changes
    branches:
      - master
    paths:
      - src
      - package.json
      - .github/workflows/ci.yml
jobs:
  test:
    runs-on: ubuntu-24.04
    name: Test on Node
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PNPM setup
        uses: pnpm/action-setup@v3

      - name: Deno Setup
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: ViTest
        run: pnpm test

      - name: Upload coverage report to coveralls.io...
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
